import 'dart:ui';

class AppColors{
  static final Color textColor=const Color(0xFFccc7c5);
  static final Color mainColor=const Color(0xFFccc7c5);
  static final Color iconColor1=const Color(0xFFccc7c5);
  static final Color iconColor2=const Color(0xFFccc7c5);
  static final Color paraColor=const Color(0xFFccc7c5);
  static final Color buttonbackgroundcolor=const Color(0xFFccc7c5);
  static final Color signcolor=const Color(0xFFccc7c5);
  static final Color titlecolor=const Color(0xFFccc7c5);
  static final Color mainBlackcolor=const Color(0xFFccc7c5);
  static final Color yellowColor=const Color(0xff931010);
  static final Color redColor = const Color(0xFFFF0000);
  static final Color greenColor = const Color(0xFF00FF00);
  static final Color blueColor = const Color(0xFF0000FF);
  static final Color orangeColor = const Color(0xFFFFA500);
  static final Color purpleColor = const Color(0xFF800080);
  static final Color pinkColor = const Color(0xFFFFC0CB);
  static final Color cyanColor = const Color(0xFF00FFFF);
  static final Color magentaColor = const Color(0xFFFF00FF);
  static final Color whiteColor = const Color(0xFFFFFFFF);
  static final Color blackColor = const Color(0xFF000000);
  static final Color grayColor = const Color(0xFF808080);
  static final Color brownColor = const Color(0xFFA52A2A);
  static final Color lightBlueColor = const Color(0xFFADD8E6);
  static final Color limeColor = const Color(0xFF00FF00);
  static final Color maroonColor = const Color(0xFF800000);
  static final Color navyColor = const Color(0xFF000080);
  static final Color oliveColor = const Color(0xFF808000);
  static final Color silverColor = const Color(0xFFC0C0C0);
  static final Color tealColor = const Color(0xFF008080);
  static final Color goldColor = const Color(0xFFFFD700);
  static final Color indigoColor = const Color(0xFF4B0082);
  static final Color lavenderColor = const Color(0xFFE6E6FA);
  static final Color salmonColor = const Color(0xFFFA8072);
  static final Color turquoiseColor = const Color(0xFF40E0D0);
  static final Color violetColor = const Color(0xFFEE82EE);
  static final Color coralColor = const Color(0xFFFF7F50);
  static final Color khakiColor = const Color(0xFFF0E68C);
  static final Color plumColor = const Color(0xFFDDA0DD);
  static final Color steelBlueColor = const Color(0xFF4682B4);
  static final Color tomatoColor = const Color(0xFFFF6347);
}