import 'dart:ui';

class AppColors{
  static const Color textColor=Color(0xFFccc7c5);
  static const Color mainColor=Color(0xFFccc7c5);
  static const Color iconColor1=Color(0xFFccc7c5);
  static const Color iconColor2=Color(0xFFccc7c5);
  static const Color paraColor=Color(0xFFccc7c5);
  static const Color buttonbackgroundcolor=Color(0xFFccc7c5);
  static const Color signcolor=Color(0xFFccc7c5);
  static const Color titlecolor=Color(0xFFccc7c5);
  static const Color mainBlackcolor=Color(0xFFccc7c5);
  static const Color yellowColor=Color(0xff931010);
  static const Color redColor = Color(0xFFFF0000);
  static const Color greenColor = Color(0xFF00FF00);
  static const Color blueColor = Color(0xFF0000FF);
  static const Color orangeColor = Color(0xFFFFA500);
  static const Color purpleColor = Color(0xFF800080);
  static const Color pinkColor = Color(0xFFFFC0CB);
  static const Color cyanColor = Color(0xFF00FFFF);
  static const Color magentaColor = Color(0xFFFF00FF);
  static const Color whiteColor = Color(0xFFFFFFFF);
  static const Color blackColor = Color(0xFF000000);
  static const Color grayColor = Color(0xFF808080);
  static const Color brownColor = Color(0xFFA52A2A);
  static const Color lightBlueColor = Color(0xFFADD8E6);
  static const Color limeColor = Color(0xFF00FF00);
  static const Color maroonColor = Color(0xFF800000);
  static const Color navyColor = Color(0xFF000080);
  static const Color oliveColor = Color(0xFF808000);
  static const Color silverColor = Color(0xFFC0C0C0);
  static const Color tealColor = Color(0xFF008080);
  static const Color goldColor = Color(0xFFFFD700);
  static const Color indigoColor = Color(0xFF4B0082);
  static const Color lavenderColor = Color(0xFFE6E6FA);
  static const Color salmonColor = Color(0xFFFA8072);
  static const Color turquoiseColor = Color(0xFF40E0D0);
  static const Color violetColor = Color(0xFFEE82EE);
  static const Color coralColor = Color(0xFFFF7F50);
  static const Color khakiColor = Color(0xFFF0E68C);
  static const Color plumColor = Color(0xFFDDA0DD);
  static const Color steelBlueColor = Color(0xFF4682B4);
  static const Color tomatoColor = Color(0xFFFF6347);
}